from setuptools import setup

setup(name='online_dmd',
      version='0.1-alpha',
      description='a python library implementing Zhang et al. online DMD methods',
      classifiers=['Development Status :: 3 - Alpha',
                   'License :: OSI Approved :: MIT License',
                   'Programming Language :: Python :: 3.6',
                   'Topic :: Scientific/Engineering :: Physics',
                   'Topic :: Scientific/Engineering :: Mathematics',
                   'Topic :: Scientific/Engineering :: Information Analysis'],
      keywords='online dynamic mode decomposition dmd',
      url='http://github.com/VArdulov/online_dmd',
      author='Victor Ardulov',
      author_email='ardulov@usc.edu',
      license='MIT',
      packages=['online_dmd'],
      install_requires=['numpy'],
      include_package_data=True,
      zip_safe=False)
